<?php

namespace Airi\UserBundle\Entity;

use Doctrine\ORM\EntityManager;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}
